version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: CREATING API CREDENTIALS FILE
        command: touch gradle.properties
    - run:
        name: PUTTING PUBLIC API KEY
        command: echo marvelPublicKey=\"0000\" >> gradle.properties
    - run:
        name: PUTTING PRIVATE API KEY
        command: echo marvelPrivateKey=\"0000\" >> gradle.properties
    - run:
        name: ACCEPTING ANDROID LICENSES #if permission for Gradlew Dependencies fail, use this.
        command: yes | sdkmanager --licenses || exit 0
    - run:
        name: CHMOD PERMISSIONS #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: DOWNLOAD DEPENDENCIES
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: CLEAN BUILD
        command: ./gradlew clean
    - run:
        name: RUN LINT
        command: ./gradlew lintDebug
    - run:
        name: RUN UNIT TESTS
        command: ./gradlew testDebugUnitTest --stacktrace
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: app/build/reports
        destination: reports
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: app/build/test-results
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
